---
name: First Deployment Check
description: Check to see if this is the first deployment
inputs:
  managementGroupId:
    description: 'The management group id'
    required: true

runs:
  using: "composite"
  steps:
    - name: First Deployment Check
      id: firstDeployment
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          $intRootMgId = $env:MANAGEMENT_GROUP_ID_PREFIX + $env:INTERMEDIATE_ROOT_MANAGEMENT_GROUP_ID + $env:MANAGEMENT_GROUP_ID_POSTFIX

          $managementGroup = Get-AzManagementGroup -GroupName $intRootMgId -Expand

          $firstDeployment = $true

          if($managementGroup -eq $null) {
            Write-Warning "Cannot find the $intRootMgId Management Group, so assuming this is the first deployment."
          } else {
            Write-Host "Found the $intRootMgId Management Group."
            $children = $managementGroup.Children | Where-Object { $_.Type -eq "Microsoft.Management/managementGroups" }
            if($children.Count -gt 0) {
              Write-Host "The $intRootMgId Management Group has child management groups, so this is NOT the first deployment."
              $firstDeployment = $false
            } else {
              Write-Host "The $intRootMgId Management Group has NO child management groups, so assuming this is the first deployment."
            }
          }
          echo "firstDeployment=$firstDeployment" >> $env:GITHUB_ENV
      env:
        MANAGEMENT_GROUP_ID: ${{ inputs.managementGroupId }}
